### PR TITLE
Add Keyboard scrolling to Feature Selector

### PR DESCRIPTION
**Pull request by sdelamo**
See: https://github.com/micronaut-projects/micronaut-starter-ui/issues/5

This moves the PR https://github.com/micronaut-projects/static-website/pull/63 to this repo: 

It relates to https://github.com/micronaut-projects/micronaut-starter/issues/204

@eahrold :

> I'm up for suggestions on the specifics of key handling.
> 
> Current Keymapping
> Up - Moves 50px up
> Down - Moves 50px down
> Left - Jumps to previous Category
> Right - Jumps to next Category
> Page Down - Jumps to next visible area (+ modal height)
> Page Up - Jumps to prev visible area (+ modal height)

@graemerocher 
> Could we add shortcuts for the 4 buttons as well?

@eahrold 
> Absolutely, that's a great idea.

@graemerocher 
> other impls seems to use CMD+RETURN for generate

### CODE REVIEW

**Comment by sdelamo** [comment]
+1 for shorcuts for every button. 

Moreover, It would be fantastic to be able to generate an app just with the mouse. Thus, shortcuts to change between language, build and test framework.

**Comment by sdelamo** [comment]
I've added to https://github.com/micronaut-projects/micronaut-starter-ui/issues/5 the wish list.

**Comment by ilopmar** [comment]
@eahrold is this already deployed? I'm trying some of [this shortcuts](https://github.com/micronaut-projects/micronaut-starter-ui/pull/1/files#diff-ae32aad876fbde919ccc8a07d0c28f31930bcf8d9f586315df9b0cd5274cef42) but they don't work for me. I'm on Linux, not on Mac.

**Comment by eahrold** [comment]
Not deployed, I’m bundling a 2.3.2 branch with a number of features for a release.

**Comment by ilopmar** [comment]
Thanks for the clarification. Regarding Linux, which key should I use, `Alt`?

**Comment by eahrold** [comment]
Yeah this is where I landed

https://github.com/micronaut-projects/micronaut-starter-ui/blob/release/v2.3.2/main/src/main/js/launch/src/constants/shortcuts.js

**Pull request merged**
